не удалось отправить файл на runner
games
Traceback (most recent call last):
  File "/home/runner/work/TLVSsolution/TLVSsolution/Content_prod/logics/modules/runner_push.py", line 30, in runner_push
    json.dump(file_content, f, skipkeys=True, ensure_ascii=False, indent=2)
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/json/__init__.py", line 179, in dump
    for chunk in iterable:
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/json/encoder.py", line 429, in _iterencode
    yield from _iterencode_list(o, _current_indent_level)
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/json/encoder.py", line 325, in _iterencode_list
    yield from chunks
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/json/encoder.py", line 325, in _iterencode_list
    yield from chunks
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type datetime is not JSON serializable
